---
settings:
  name: BlueXP
  platform: cloud
  search: bluexp-relnotes,bluexp-setup-admin,bluexp-cloud-volumes-ontap,bluexp-ontap-onprem,bluexp-azure-netapp-files,bluexp-fsx-ontap,bluexp-cloud-volumes-service-gcp,bluexp-kubernetes,bluexp-remediation,bluexp-backup-recovery,bluexp-copy-sync,bluexp-classification,bluexp-tiering,bluexp-ransomware-protection,bluexp-replication,bluexp-edge-caching,bluexp-cloud-ops,bluexp-automation,cloud-volumes-ontap-relnotes,bluexp-storagegrid,bluexp-e-series,bluexp-s3-storage,bluexp-economic-efficiency,bluexp-operational-resiliency,bluexp-digital-wallet,bluexp-blob-storage,bluexp-reports,bluexp-volume-caching,bluexp-disaster-recovery
  internal:
    pdf_enabled: false
    lipi_enabled: true
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Toda la documentación de BlueXP
    url: "/index.html"
product-family:
  sidebarlinks:
  - title: Todo
    tags: all
    class: active
  - title: API
    tags: api
  - title: Conectores y cuentas
    tags: admin
  - title: Extensiones
    tags: extension
  - title: Gobernanza
    tags: governance
  - title: Salud
    tags: health
  - title: Movilidad
    tags: mobility
  - title: Protección
    tags: protection
  - title: Reducida
    tags: storage
  tiles:
  - title: Bienvenido a BlueXP
    icon: "./media/icon-docs.png"
    url: concept-overview.html
    summary: Más información sobre la introducción de BlueXP.
    tags: all
  - title: Configuración y administración
    icon: "./media/icon-admin.png"
    url: https://docs.netapp.com/us-en/bluexp-setup-admin/index.html
    summary: Aprenda a empezar a usar BlueXP y a administrar conectores, cuentas y
      mucho más.
    tags: all,admin
  - title: Notas de la versión
    icon: "./media/icon-docs.png"
    url: https://docs.netapp.com/us-en/bluexp-relnotes/index.html
    summary: Conozca las novedades de BlueXP.
    tags: all
  - title: Amazon FSX para ONTAP de NetApp
    icon: "./media/icon-fsx.png"
    url: https://docs.netapp.com/us-en/bluexp-fsx-ontap/index.html
    summary: Utilice todas las funcionalidades de ONTAP como servicio nativo gestionado
      por AWS.
    tags: all,storage,aws
  - title: Almacenamiento Amazon S3
    icon: "./media/icon-s3.png"
    url: https://docs.netapp.com/us-en/bluexp-s3-storage/index.html
    summary: Descubra y gestione los bloques de Amazon S3 en sus cuentas de AWS.
    tags: all,storage,aws
  - title: API
    icon: "./media/icon-api.png"
    url: https://docs.netapp.com/us-en/bluexp-automation/index.html
    summary: Administre sus recursos basados en la nube mediante programación.
    tags: all,api
  - title: Almacenamiento de Azure Blob
    icon: "./media/icon-azure-blob.png"
    url: https://docs.netapp.com/us-en/bluexp-blob-storage/index.html
    summary: Descubre y gestiona el almacenamiento de Azure Blob en tus suscripciones
      a Azure.
    tags: all,storage
  - title: Azure NetApp Files
    icon: "./media/icon-anf.png"
    url: https://docs.netapp.com/us-en/bluexp-azure-netapp-files/index.html
    summary: Servicio de almacenamiento de archivos de alto rendimiento para las aplicaciones
      principales de la empresa.
    tags: all,storage,azure
  - title: Backup y recuperación de datos (Cloud Backup)
    icon: "./media/icon-backup.png"
    url: https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html
    summary: Realice backups y restauraciones de datos en el cloud y en las instalaciones.
    tags: all,aws,azure,gcp,protection
  - title: Clasificación (Cloud Data Sense)
    icon: "./media/icon-data-sense.png"
    url: https://docs.netapp.com/us-en/bluexp-classification/index.html
    summary: Consiga que los datos de aplicaciones y los entornos de cloud estén listos
      para la privacidad.
    tags: all,governance,aws,azure,gcp
  - title: Operaciones de cloud (computación)
    icon: "./media/icon-compute.png"
    url: https://docs.netapp.com/us-en/bluexp-cloud-ops/index.html
    summary: Obtenga visibilidad de sus gastos en tecnología cloud e identifique posibles
      ahorros.
    tags: all,aws,extension
  - title: Cloud Volumes ONTAP
    icon: "./media/icon-cvo.png"
    url: https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html
    summary: Haga que su almacenamiento en cloud sea más asequible, inteligente, conforme
      a las normativas y seguro.
    tags: all,storage,aws,azure,gcp
  - title: Cloud Volumes Service para Google Cloud
    icon: "./media/icon-cvs.png"
    url: https://docs.netapp.com/us-en/bluexp-cloud-volumes-service-gcp/index.html
    summary: Asegure, proteja y acelere su almacenamiento de archivos.
    tags: all,storage,gcp
  - title: Copia y sincronización (Cloud Sync)
    icon: "./media/icon-sync.png"
    url: https://docs.netapp.com/us-en/bluexp-copy-sync/index.html
    summary: Sincronice datos entre almacenes de datos en las instalaciones y en el
      cloud.
    tags: all,aws,azure,gcp,mobility
  - title: Asesor digital (Active IQ)
    icon: "./media/icon-activeiq.png"
    url: https://docs.netapp.com/us-en/active-iq/index.html
    tags: all,health
    summary: Información procesable para un estado óptimo del almacenamiento.
  - title: Cartera digital
    icon: "./media/digital-wallet.png"
    url: https://docs.netapp.com/us-en/bluexp-digital-wallet/index.html
    tags: all,governance
    summary: Administre y supervise sus licencias y suscripciones.
  - title: Recuperación tras siniestros
    icon: "./media/icon-disaster-recovery.png"
    url: https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html
    tags: all,protection
    summary: Protege las cargas de trabajo de VMware on-premises usando VMware Cloud
      on Amazon FSx para ONTAP como sitio de recuperación ante desastres.
  - title: Sistemas E-Series
    icon: "./media/icon-e-series.png"
    url: https://docs.netapp.com/us-en/bluexp-e-series/index.html
    summary: Descubra los sistemas E-Series para obtener una visión completa de los
      datos en su multicloud híbrido.
    tags: all,storage
  - title: Eficiencia económica
    icon: "./media/icon-economic-efficiency.png"
    url: https://docs.netapp.com/us-en/bluexp-economic-efficiency/index.html
    summary: Identificar clusters con baja capacidad actual o prevista e implementar
      niveles de datos o recomendaciones adicionales de capacidad.
    tags: all,governance
  - title: Almacenamiento en caché en el perímetro (Global File Cache)
    icon: "./media/icon-cache.png"
    url: https://docs.netapp.com/us-en/bluexp-edge-caching/index.html
    summary: Haga posible el uso compartido de archivos global en tiempo real para
      su personal distribuido.
    tags: all,mobility,aws,azure,gcp
  - title: Google Cloud Storage
    icon: "./media/icon-google-cloud-storage.png"
    url: https://docs.netapp.com/us-en/bluexp-google-cloud-storage/index.html
    summary: Descubre y gestiona los buckets de Cloud Storage en tu cuenta de Google.
    tags: all,storage
  - title: Clústeres de Kubernetes
    icon: "./media/icon-kubernetes.png"
    url: https://docs.netapp.com/us-en/bluexp-kubernetes/index.html
    summary: Gestión de datos avanzada de los clústeres de Kubernetes en el cloud
      híbrido.
    tags: all,storage,aws,azure
  - title: Informes de migración
    icon: "./media/icon-reports.png"
    url: https://docs.netapp.com/us-en/bluexp-reports/index.html
    summary: Identifique el número de archivos, la profundidad y la amplitud de los
      árboles de sistemas de archivos, los archivos de mayor tamaño y mucho más en
      su entorno de almacenamiento.
    tags: all,storage
  - title: Clústeres de ONTAP en las instalaciones
    icon: "./media/icon-onprem.png"
    url: https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html
    summary: Gestione sus sistemas AFF y FAS de NetApp desde BlueXP con los servicios
      de datos de System Manager y BlueXP.
    tags: all,storage
  - title: Resiliencia operativa
    icon: "./media/icon-op-resiliency.png"
    url: https://docs.netapp.com/us-en/bluexp-operational-resiliency/index.html
    summary: Implementar las soluciones de riesgo de configuración automatizadas del
      firmware y el software para mantener el estado de los clústeres ONTAP.
    tags: all,health
  - title: Protección contra ransomware
    icon: "./media/icon-ransomware.png"
    url: https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html
    summary: Evalúe cómo la resiliencia de sus datos frente a un ataque cibernético.
    tags: all,governance,protection
  - title: Solución (AppTemplate)
    icon: "./media/icon-app-template.png"
    url: https://docs.netapp.com/us-en/bluexp-remediation/index.html
    summary: Automatizar acciones en BlueXP para acelerar la provisión y eliminar
      el trabajo manual.
    tags: all,health
  - title: Replicación
    icon: "./media/icon-replication.png"
    url: https://docs.netapp.com/us-en/bluexp-replication/index.html
    summary: Replicar datos entre sistemas de almacenamiento para dar soporte a backup
      y recuperación ante desastres
    tags: all,protection
  - title: StorageGRID
    icon: "./media/icon-storagegrid.png"
    url: https://docs.netapp.com/us-en/bluexp-storagegrid/index.html
    summary: Descubra y gestione sus sistemas StorageGRID.
    tags: all,storage
  - title: Panel de sostenibilidad
    icon: "./media/icon-sustainability.png"
    url: https://docs.netapp.com/us-en/active-iq/concept_understand_sustainability_dashboard.html
    summary: Analice la sostenibilidad de sus sistemas de almacenamiento.
    tags: all,governance
  - title: Organización en niveles (organización en niveles del cloud)
    icon: "./media/icon-tiering.png"
    url: https://docs.netapp.com/us-en/bluexp-tiering/index.html
    summary: Lleve su almacenamiento ONTAP en las instalaciones al cloud.
    tags: all,aws,azure,gcp,mobility
  - title: Almacenamiento en caché de volúmenes
    icon: "./media/icon-volume-caching.png"
    url: https://docs.netapp.com/us-en/bluexp-volume-caching/index.html
    summary: Cree un volumen de caché editable para acelerar el acceso a los datos
      o descargar el tráfico de volúmenes con un acceso frecuente.
    tags: all,mobility
