---
settings:
  name: BlueXP
  platform: cloud
  search: cloud-manager-relnotes,cloud-manager-setup-admin,cloud-manager-cloud-volumes-ontap,cloud-manager-ontap-onprem,cloud-manager-azure-netapp-files,cloud-manager-fsx-ontap,cloud-manager-cloud-volumes-service-aws,cloud-manager-cloud-volumes-service-gcp,cloud-manager-kubernetes,cloud-manager-app-template,cloud-manager-backup-restore,cloud-manager-sync,cloud-manager-data-sense,cloud-manager-tiering,cloud-manager-ransomware,cloud-manager-replication,cloud-manager-file-cache,cloud-manager-compute,cloud-manager-automation,cloud-volumes-ontap-relnotes,cloud-manager-storagegrid,cloud-manager-e-series,bluexp-s3-storage
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr
sidebar:
  entries:
  - title: Toda la documentación de BlueXP
    url: "/index.html"
product-family:
  sidebarlinks:
  - title: Todo
    tags: all
    class: active
  - title: API
    tags: api
  - title: Conectores y cuentas
    tags: admin
  - title: Extensiones
    tags: extension
  - title: Gobernanza
    tags: governance
  - title: Salud
    tags: health
  - title: Información
    tags: insights
  - title: Movilidad
    tags: mobility
  - title: Protección
    tags: protection
  - title: Reducida
    tags: storage
  tiles:
  - title: Bienvenido a BlueXP
    icon: "./media/icon-docs.png"
    url: concept-overview.html
    summary: Más información sobre la introducción de BlueXP.
    tags: all
  - title: Configuración y administración
    icon: "./media/icon-admin.png"
    url: https://docs.netapp.com/us-en/cloud-manager-setup-admin/index.html
    summary: Aprenda a empezar a usar BlueXP y a administrar conectores, cuentas y
      mucho más.
    tags: all, admin
  - title: Notas de la versión
    icon: "./media/icon-docs.png"
    url: https://docs.netapp.com/us-en/cloud-manager-relnotes/index.html
    summary: Conozca las novedades de BlueXP.
    tags: all
  - title: Amazon FSX para ONTAP
    icon: "./media/icon-fsx.png"
    url: https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/index.html
    summary: Utilice todas las funcionalidades de ONTAP como servicio nativo gestionado
      por AWS.
    tags: all, storage, aws
  - title: Almacenamiento Amazon S3
    icon: "./media/icon-s3.png"
    url: https://docs.netapp.com/us-en/bluexp-s3-storage/index.html
    summary: Descubra y gestione los bloques de Amazon S3 en sus cuentas de AWS.
    tags: all, storage, aws
  - title: API
    icon: "./media/icon-api.png"
    url: https://docs.netapp.com/us-en/cloud-manager-automation/index.html
    summary: Administre sus recursos basados en la nube mediante programación.
    tags: all, api
  - title: AppTemplate
    icon: "./media/icon-app-template.png"
    url: https://docs.netapp.com/us-en/cloud-manager-app-template/index.html
    summary: Automatizar acciones en BlueXP para acelerar la provisión y eliminar
      el trabajo manual.
    tags: all, health
  - title: Azure NetApp Files
    icon: "./media/icon-anf.png"
    url: https://docs.netapp.com/us-en/cloud-manager-azure-netapp-files/index.html
    summary: Servicio de almacenamiento de archivos de alto rendimiento para las aplicaciones
      principales de la empresa.
    tags: all, storage, azure
  - title: Backup en el cloud
    icon: "./media/icon-backup.png"
    url: https://docs.netapp.com/us-en/cloud-manager-backup-restore/index.html
    summary: Realice backups y restauraciones de datos en el cloud y en las instalaciones.
    tags: all, aws, azure, gcp, protection
  - title: Cloud Data SENSE
    icon: "./media/icon-data-sense.png"
    url: https://docs.netapp.com/us-en/cloud-manager-data-sense/index.html
    summary: Consiga que los datos de aplicaciones y los entornos de cloud estén listos
      para la privacidad.
    tags: all, governance, aws, azure, gcp
  - title: Cloud Insights
    icon: "./media/icon-monitoring.png"
    url: https://docs.netapp.com/us-en/cloudinsights/
    summary: Controle el rendimiento y el uso de sus cargas de trabajo del cloud.
    tags: all, insights
  - title: Cloud Sync
    icon: "./media/icon-sync.png"
    url: https://docs.netapp.com/us-en/cloud-manager-sync/index.html
    summary: Sincronice datos entre almacenes de datos en las instalaciones y en el
      cloud.
    tags: all, aws, azure, gcp, mobility
  - title: Organización en niveles del cloud
    icon: "./media/icon-tiering.png"
    url: https://docs.netapp.com/us-en/cloud-manager-tiering/index.html
    summary: Lleve su almacenamiento ONTAP en las instalaciones al cloud.
    tags: all, aws, azure, gcp, mobility
  - title: Cloud Volumes ONTAP
    icon: "./media/icon-cvo.png"
    url: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/index.html
    summary: Haga que su almacenamiento en cloud sea más asequible, inteligente, conforme
      a las normativas y seguro.
    tags: all, storage, aws, azure, gcp
  - title: Cloud Volumes Service para AWS
    icon: "./media/icon-cvs.png"
    url: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-service-aws/index.html
    summary: Un servicio de archivos nativo del cloud con rendimiento all-flash.
    tags: all, storage, aws
  - title: Cloud Volumes Service para Google Cloud
    icon: "./media/icon-cvs.png"
    url: https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-service-gcp/index.html
    summary: Asegure, proteja y acelere su almacenamiento de archivos.
    tags: all, storage, gcp
  - title: Informática
    icon: "./media/icon-compute.png"
    url: https://docs.netapp.com/us-en/cloud-manager-compute/index.html
    summary: Obtenga visibilidad de sus gastos en tecnología cloud e identifique posibles
      ahorros.
    tags: all, aws, extension
  - title: Asesor digital (anteriormente Active IQ)
    icon: "./media/icon-activeiq.png"
    url: https://docs.netapp.com/us-en/active-iq/index.html
    tags: all, health
    summary: Información procesable para un estado óptimo del almacenamiento.
  - title: Cartera digital
    icon: "./media/digital-wallet.png"
    url: https://docs.netapp.com/us-en/bluexp-digital-wallet/index.html
    tags: all, governance
    summary: Administre y supervise sus licencias y suscripciones.
  - title: Sistemas E-Series
    icon: "./media/icon-e-series.png"
    url: https://docs.netapp.com/us-en/cloud-manager-e-series/index.html
    summary: Descubra los sistemas E-Series para obtener una visión completa de los
      datos en su multicloud híbrido.
    tags: all, storage
  - title: Eficiencia económica
    icon: "./media/icon-economic-efficiency.png"
    url: https://docs.netapp.com/us-en/bluexp-economic-efficiency/index.html
    summary: Identificar clusters con baja capacidad actual o prevista e implementar
      niveles de datos o recomendaciones adicionales de capacidad.
    tags: all, governance
  - title: Caché de archivos global
    icon: "./media/icon-cache.png"
    url: https://docs.netapp.com/us-en/cloud-manager-file-cache/index.html
    summary: Haga posible el uso compartido de archivos global en tiempo real para
      su personal distribuido.
    tags: all, mobility, aws, azure, gcp
  - title: Clústeres de Kubernetes
    icon: "./media/icon-kubernetes.png"
    url: https://docs.netapp.com/us-en/cloud-manager-kubernetes/index.html
    summary: Gestión de datos avanzada de los clústeres de Kubernetes en el cloud
      híbrido.
    tags: all, storage, aws, azure
  - title: Clústeres de ONTAP en las instalaciones
    icon: "./media/icon-onprem.png"
    url: https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html
    summary: Gestione sus sistemas AFF y FAS de NetApp desde BlueXP con los servicios
      de datos de System Manager y BlueXP.
    tags: all, storage
  - title: Resiliencia operativa
    icon: "./media/icon-op-resiliency.png"
    url: https://docs.netapp.com/us-en/bluexp-operational-resiliency/index.html
    summary: Implementar las soluciones de riesgo de configuración automatizadas del
      firmware y el software para mantener el estado de los clústeres ONTAP.
    tags: all, health
  - title: Protección contra ransomware
    icon: "./media/icon-ransomware.png"
    url: https://docs.netapp.com/us-en/cloud-manager-ransomware/index.html
    summary: Evalúe cómo la resiliencia de sus datos frente a un ataque cibernético.
    tags: all, governance
  - title: Replicación
    icon: "./media/icon-replication.png"
    url: https://docs.netapp.com/us-en/cloud-manager-replication/index.html
    summary: Replicar datos entre sistemas de almacenamiento para dar soporte a backup
      y recuperación ante desastres
    tags: all, protection
  - title: StorageGRID
    icon: "./media/icon-storagegrid.png"
    url: https://docs.netapp.com/us-en/cloud-manager-storagegrid/index.html
    summary: Descubra y gestione sus sistemas StorageGRID.
    tags: all, storage
